# Generated by Django 5.2.1 on 2025-06-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='design_upload',
        ),
    ]
