# Generated by Django 5.2.1 on 2025-07-05 12:53

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_design_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_specific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('size', models.CharField(max_length=9)),
                ('notes', models.TextField(blank=True, null=True)),
                ('design', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=233000000000, max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default='Small', max_length=9),
            preserve_default=False,
        ),
    ]
